#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker-1"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "f78e1b54f66d4563a03a5b10d93c3670" }
]

[assets]
directory = "./public"
